# Use for local dev
FROM python:3.8
LABEL maintainer "Daniel Stratti <daniels@vamp.me>"

WORKDIR /app

# Install server
# RUN apt update

COPY requirements.txt /
RUN pip install -r /requirements.txt

COPY ./ ./
COPY ./vamp-cast-staging-e5ffa19bffe8.json ./

EXPOSE 8080
#EXPOSE 443

CMD ["python", "./app.py"]

# docker build . -t cast-exp
# docker run -it -v $PWD:/app -p 8080:8080 --env-file=.env cast-exp
